language: node_js

# test on two node.js versions: 0.8
node_js:
  - 8.4.0

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

install:
  - npm install

script:
  - standard
  - npm run data-init-dev
  - npm test


before_deploy:
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - ssh-keyscan -t rsa,ecdsa-sha2-nistp256 -p $DEPLOY_PORT $DEPLOY_HOST >> $HOME/.ssh/known_hosts
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST cd lab-wiki-backend && git checkout $TRAVIS_BRANCH && git pull origin $TRAVIS_BRANCH && rm package-lock.json -f && npm install
    on:
      branch:
        - master
        - feature/auto-deploy

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  email:
    recipients:
      - labwiki@nlg.csie.ntu.edu.tw
    on_success: never # default: change
    on_failure: always # default: always
