require('./cfp-service').start()
console.log('CFP service running...')
require('./mail-service')
console.log('Mail service running...')
// require('./seminar-service')
// console.log('Seminar service running...')
